### PR TITLE
ApigatewayHandler, Redirect response cors header

### PR DESCRIPTION
**Pull request by monaullah**
Set header `Access-Control-Allow-Origin` to environment variable `ALLOWED_ORIGIN` in ApigatewayHandler for redirect responses.

### CODE REVIEW

**Comment by ketilaa** [comment]
Hva er bakgrunnen for denne PR'en?

**Review by sondrev — COMMENTED** [review]
what happens to existing apis that have not set this env value? will a null value of allowe origins be different than no header?

**Comment by monaullah** [comment]
@sondrev Existing init method in `ApiGatewayHandler`:
```
@Override
public void init(OutputStream outputStream, Context context) {
    this.allowedOrigin = environment.readEnv(ALLOWED_ORIGIN_ENV);
    super.init(outputStream, context);
}
```

**Review by sondrev — APPROVED** [review]
code looks good

**Review by brinxmat — APPROVED** [review]

**Pull request merged**
